### PR TITLE
change pycord to pypi stable version

### PR DESCRIPTION
**Pull request by Naman23-coder**

### CODE REVIEW

**Comment by rtk-rnjn** [comment]
I am afraid that changing the requirements could break the bot

**Review by rtk-rnjn — COMMENTED** [review]
Probably, this needs to be done after actual stable release of py-cord 2.0

**Comment by Naman23-coder** [comment]
@rtk-rnjn okay, so should I close pull request

**Comment by rtk-rnjn** [comment]
Thanks for your contribution, tho'

**Pull request closed without merging**
